### ISSUE TITLE
Add WebOb v1 compatibility

### ISSUE THREAD

**Issue by hekevintran** [2degrees/django-wsgi#3]
I am using buildout with
Django 1.2.5
Paste 1.7.5.1
PasteDeploy 1.3.4
PasteScript 1.7.3
WebOb 1.0.7
twod.wsgi 1.0

I run the paster server:
    $ ./bin/paster serve --app-name=development --server-name=development --reload settings.ini

The Django application starts and everything seems normal until I try to run a view that accesses the 'POST' attribute on the request object. When that happens the __getattr__() method of TwodWSGIRequest is called. This looks for 'POST' in self.environ['webob.adhoc_attrs']. Since that doesn't exist, it raises AttributeError.

I don't understand this at all because 'POST' is supposed to be an attribute on TwodWSGIRequest just like it is on Django's HttpRequest class.

The really weird part is that the request is fine after I inspect it manually during a debugging session. I put a breakpoint before the code that accesses the 'POST' attribute:

    > /Users/haitran/Desktop/project/apps/account/views.py(36)login()
         35     import ipdb; ipdb.set_trace()
    ---> 36     if request.method == 'POST':
         37         form = LoginForm(request.POST)

    ipdb> request

    <WSGIRequest
    GET:<QueryDict: {}>,
    POST:<could not parse>,   # <-- why is this not correct?
     ...
     'wsgi.version': (1, 0)}>

    ipdb> request

    <WSGIRequest
    GET:<QueryDict: {}>,
    POST:<QueryDict: {u'next_url': [u''], u'password': [u'passwd'], u'email': [u'kevin.tran@obnob.com']}>,
     ...
     'wsgi.version': (1, 0)}>

Note that the first time I look at the request object, the 'POST' attribute is printed as "<could not parse>". The second time I look at the request object, everything is fine with the POST attribute. 

This problem does not happen when using WebOb 0.9.8. It happens when using WebOb 1.0.7.

**Comment by gnarea** [comment]
This is now fixed in django-wsgi v1.0b1.
