### ISSUE TITLE
Support for Django 2+

### ISSUE THREAD

**Issue by AntonOfTheWoods** [2degrees/django-wsgi#8]
If anyone is still around here - with Django 1.10 no longer supported upstream, it would be great to get the code 2+ compliant. There may be other issues I haven't encountered yet but https://docs.djangoproject.com/en/1.11/ref/contrib/auth/#django.contrib.auth.models.User.is_authenticated
has changed from a method to a bool.

**Comment by franciscoruiz** [comment]
This project is no longer maintained.
